apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-example
  namespace: eks-example
  labels:
    app: eks-example
  annotations:
    # Container Image Automated Updates
    flux.weave.works/automated: "true" //*TO-DO*
spec:
  replicas: 1 //*To-DO*
  selector:
    matchLabels:
      app: eks-example
  template:
    metadata:
      labels:
        app: eks-example
    spec:
      containers:
      - name: eks-example
        image: 306478720536.dkr.ecr.us-east-1.amazonaws.com/eks-example  //*TO-DO*
        imagePullPolicy: IfNotPresent
                resources:
          requests: 
            memory: "64Mi" //*TO-DO*
            cpu: "400m" //*TO-DO*
          limits:
            memory: "64Mi"
            cpu: "400m"
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
